### ISSUE TITLE
Dimension Sync

### ISSUE THREAD

**Issue by CubewisePacific** [CubewisePacific/PCC#1]
**Requirements:**
- [ ] Use PCC TM1 objects and consistent coding
- [ ] Copy from existing dimension to existing (same) dimension or create new (with same name or new name)
- [ ] Options to copy attributes (i.e. add the attributes to the target dim) and/or attribute values)
- [ ] 

 
**Sub-Tasks:**
- [ ] sub-task
- [ ] sub-task
- [ ] sub-task
